application: its-hackademic
version: 2-3-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  mime_type: text/html
  static_files: static/index.html
  upload: static/index.html

- url: /codelabs/?
  mime_type: text/html
  static_files: static/codelabs.html
  upload: static/codelabs.html

- url: /static/codelabs/1-polymer-first-app/
  mime_type: text/html
  static_files: static/codelabs/1-polymer-first-app/index.html
  upload: static/codelabs/1-polymer-first-app/index.html

- url: /static/codelabs/2-polymer-build-maps/
  mime_type: text/html
  static_files: static/codelabs/2-polymer-build-maps/index.html
  upload: static/codelabs/2-polymer-build-maps/index.html

- url: /static/codelabs/3-polymer-build-mobile/
  mime_type: text/html
  static_files: static/codelabs/3-polymer-build-mobile/index.html
  upload: static/codelabs/3-polymer-build-mobile/index.html

- url: /static/codelabs/4-polymer-drive-client/
  mime_type: text/html
  static_files: static/codelabs/4-polymer-drive-client/index.html
  upload: static/codelabs/4-polymer-drive-client/index.html

- url: /static/codelabs/5-polymer-map-visualization/
  mime_type: text/html
  static_files: static/codelabs/5-polymer-map-visualization/index.html
  upload: static/codelabs/5-polymer-map-visualization/index.html

- url: /completed/?
  mime_type: text/html
  static_files: static/completed.html
  upload: static/completed.html

- url: /metadata/
  script: app.app

- url: /static
  application_readable: true
  static_dir: static
